export const WORKOUT_CONFIG = {
  strength: {
    label: 'Strength',
    icon: '💪',
    weeklyTarget: 3,
    subtypes: ['climbing', 'weights', 'HIIT', 'Orange Theory'],
    subtypeIcons: { climbing: '🧗', weights: '🏋️', HIIT: '💥', 'Orange Theory': '🔶' },
    color: 'blue',
    accentClass: 'text-blue-400',
    bgClass: 'bg-blue-400/10',
    borderClass: 'border-blue-400/30',
    arcColor: '#60a5fa',
  },
  cardio: {
    label: 'Cardio',
    icon: '🏃',
    weeklyTarget: 2,
    subtypes: ['bike', 'run', 'row', 'swimming'],
    subtypeIcons: { bike: '🚴', run: '🏃', row: '🚣', swimming: '🏊' },
    color: 'cyan',
    accentClass: 'text-cyan-400',
    bgClass: 'bg-cyan-400/10',
    borderClass: 'border-cyan-400/30',
    arcColor: '#22d3ee',
  },
  plyometrics: {
    label: 'Plyometrics',
    icon: '⚡',
    weeklyTarget: 2,
    subtypes: [],
    color: 'yellow',
    accentClass: 'text-yellow-400',
    bgClass: 'bg-yellow-400/10',
    borderClass: 'border-yellow-400/30',
    arcColor: '#facc15',
  },
  stretching: {
    label: 'Stretching',
    icon: '🧘',
    weeklyTarget: 3,
    subtypes: [],
    color: 'emerald',
    accentClass: 'text-emerald-400',
    bgClass: 'bg-emerald-400/10',
    borderClass: 'border-emerald-400/30',
    arcColor: '#34d399',
  },
  team_sports: {
    label: 'Team Sports',
    icon: '⚽',
    weeklyTarget: 2,
    subtypes: ['basketball', 'soccer', 'frisbee'],
    subtypeIcons: { basketball: '🏀', soccer: '⚽', frisbee: '🥏' },
    color: 'orange',
    accentClass: 'text-orange-400',
    bgClass: 'bg-orange-400/10',
    borderClass: 'border-orange-400/30',
    arcColor: '#fb923c',
  },
}
