export const WORKOUT_CONFIG = {
  strength: {
    label: 'Strength',
    icon: '💪',
    weeklyTarget: 3,
    subtypes: ['climbing', 'weights', 'HIIT'],
    subtypeIcons: { climbing: '🧗', weights: '🏋️', HIIT: '💥' },
    color: 'blue',
    accentClass: 'text-blue-400',
    bgClass: 'bg-blue-400/10',
    borderClass: 'border-blue-400/30',
    arcColor: '#60a5fa',
  },
  cardio: {
    label: 'Cardio',
    icon: '🏃',
    weeklyTarget: 3,
    subtypes: ['run', 'bike', 'row', 'swimming', 'basketball', 'soccer', 'frisbee', 'Orange Theory'],
    subtypeIcons: { run: '🏃', bike: '🚴', row: '🚣', swimming: '🏊', basketball: '🏀', soccer: '⚽', frisbee: '🥏', 'Orange Theory': '🔶' },
    color: 'cyan',
    accentClass: 'text-cyan-400',
    bgClass: 'bg-cyan-400/10',
    borderClass: 'border-cyan-400/30',
    arcColor: '#22d3ee',
  },
  mobility: {
    label: 'Mobility',
    icon: '🤸',
    weeklyTarget: 3,
    subtypes: ['plyometrics', 'yoga', 'stretching', 'balance'],
    subtypeIcons: { plyometrics: '⚡', yoga: '🕉️', stretching: '🙆', balance: '⚖️' },
    color: 'emerald',
    accentClass: 'text-emerald-400',
    bgClass: 'bg-emerald-400/10',
    borderClass: 'border-emerald-400/30',
    arcColor: '#34d399',
  },
  mindfulness: {
    label: 'Mindfulness',
    icon: '🧘',
    weeklyTarget: 3,
    subtypes: ['meditation', 'breathing', 'journaling', 'reading'],
    subtypeIcons: { meditation: '🕯️', breathing: '💨', journaling: '📓', reading: '📚' },
    color: 'purple',
    accentClass: 'text-purple-400',
    bgClass: 'bg-purple-400/10',
    borderClass: 'border-purple-400/30',
    arcColor: '#a78bfa',
  },
}
